#Tensors

In [ ]:
import tensorflow as tf
#Tensors are nothing but n dimensional array

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,20,3,40])
print(tensor_one_d)

tf.Tensor([ 1 20  3 40], shape=(4,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,30,5],
    [45,-9,78]
])
print(tensor_two_d)

tf.Tensor(
[[ 1 30  5]
 [45 -9 78]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [ [1,2,3], [4,5,6]],
    [ [10,20,30], [30,40,50] ],
    [ [-1,-2,-3], [0,4,5] ]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [30 40 50]]

 [[-1 -2 -3]
  [ 0  4  5]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
tensor_four_d = tf.constant([
    [[ [1,2,3], [4,5,6]],
    [ [10,20,30], [30,40,50] ],
    [ [-1,-2,-3], [0,4,5] ]],

    [[ [1,2,3], [4,5,6]],
    [ [10,20,30], [30,40,50] ],
    [ [-1,-2,-3], [0,4,5] ]]
])

print(tensor_four_d) #shape(3D per 2D,2D per 3D,1D per 2D ,column num), tips: start reading from the right side

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[10 20 30]
   [30 40 50]]

  [[-1 -2 -3]
   [ 0  4  5]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[10 20 30]
   [30 40 50]]

  [[-1 -2 -3]
   [ 0  4  5]]]], shape=(2, 3, 2, 3), dtype=int32)


In [ ]:
print(tensor_four_d.ndim) #dimension of the tensors

4


In [ ]:
#Casting in different data type
tensor_one_d = tf.constant([1,-20.0004,3.2,40], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int32)

print(casted_tensor_one_d)


tf.Tensor([  1 -20   3  40], shape=(4,), dtype=int32)


In [ ]:
#Boolean tensor
tensor_bool = tf.constant([True, False, True, False])
print(tensor_bool)

tf.Tensor([ True False  True False], shape=(4,), dtype=bool)


In [ ]:
#String tensor
tensor_string = tf.constant(["Hello", "World", "Hi"])
print(tensor_string)

tf.Tensor([b'Hello' b'World' b'Hi'], shape=(3,), dtype=string)


##Numpy array to Tensor conversion

In [ ]:
#Convert Numpy array into tensors
import numpy as np

np_array = [1,2,3,4]
print(np_array)

[1, 2, 3, 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
#Other library functions

In [ ]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns = None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)


In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100, #most of the value will be sorround to 100, because mean is normally distributed
    stddev = 1.0, #if we increase this, the bell shaped curve will wider and decrease will result in narrow. wider means higher chance of getting a value
    dtype = tf.dtypes.float32,
    seed = None,
    name = None

)
print(random_tensor)

tf.Tensor(
[[101.105644 100.32712 ]
 [100.46585   99.429245]
 [ 99.27605  100.47706 ]], shape=(3, 2), dtype=float32)


Resources:
1. https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Uniform
2. https://www.acsu.buffalo.edu/~adamcunn/probability/chisquared.html
3.

In [ ]:
uniform_tensor = tf.random.uniform( #uniform means: there is equal chances for each value to pick
    [3,2,3],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor(
[[[0.85438323 0.8247545  0.01889992]
  [0.33369732 0.05054653 0.81355095]]

 [[0.12981296 0.24095511 0.7104782 ]
  [0.2691753  0.1612624  0.04256773]]

 [[0.87188005 0.80728686 0.26188958]
  [0.377419   0.24431455 0.3840127 ]]], shape=(3, 2, 3), dtype=float32)


#Tensor Indexing

In [ ]:
tensor_one_d = ([12,34,-9,89,45])
#extracting index 1 to 3 values
print(tensor_one_d[1:4]) #[minIndex : maxIndex+1]

[34, -9, 89]


In [ ]:
print(tensor_one_d[:3]) #minIndex =0

[12, 34, -9]


In [ ]:
print(tensor_one_d[2:]) #maxIndex = last index

[-9, 89, 45]


In [ ]:
print(tensor_one_d[2:-1]) # one element will remain cut from the last

[-9, 89]


In [ ]:
#2D tensor indexing
tensor_two_d = tf.constant([
    [1,30,5],
    [45,-9,78]
])
print(tensor_two_d[ 1:, 0:3]) #[row,column]

tf.Tensor([[45 -9 78]], shape=(1, 3), dtype=int32)


In [ ]:
print(tensor_two_d[...,1]) #[pick all indexex, of column]

tf.Tensor([30 -9], shape=(2,), dtype=int32)
