#Tensors

In [ ]:
import tensorflow as tf
#Tensors are nothing but n dimensional array

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,20,3,40])
print(tensor_one_d)

tf.Tensor([ 1 20  3 40], shape=(4,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,30,5],
    [45,-9,78]
])
print(tensor_two_d)

tf.Tensor(
[[ 1 30  5]
 [45 -9 78]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [ [1,2,3], [4,5,6]],
    [ [10,20,30], [30,40,50] ],
    [ [-1,-2,-3], [0,4,5] ]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [30 40 50]]

 [[-1 -2 -3]
  [ 0  4  5]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
tensor_four_d = tf.constant([
    [[ [1,2,3], [4,5,6]],
    [ [10,20,30], [30,40,50] ],
    [ [-1,-2,-3], [0,4,5] ]],

    [[ [1,2,3], [4,5,6]],
    [ [10,20,30], [30,40,50] ],
    [ [-1,-2,-3], [0,4,5] ]]
])

print(tensor_four_d) #shape(3D per 2D,2D per 3D,1D per 2D ,column num), tips: start reading from the right side

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[10 20 30]
   [30 40 50]]

  [[-1 -2 -3]
   [ 0  4  5]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[10 20 30]
   [30 40 50]]

  [[-1 -2 -3]
   [ 0  4  5]]]], shape=(2, 3, 2, 3), dtype=int32)


In [ ]:
print(tensor_four_d.ndim) #dimension of the tensors

4


In [ ]:
#Casting in different data type
tensor_one_d = tf.constant([1,-20.0004,3.2,40], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int32)

print(casted_tensor_one_d)


tf.Tensor([  1 -20   3  40], shape=(4,), dtype=int32)


In [ ]:
#Boolean tensor
tensor_bool = tf.constant([True, False, True, False])
print(tensor_bool)

tf.Tensor([ True False  True False], shape=(4,), dtype=bool)


In [ ]:
#String tensor
tensor_string = tf.constant(["Hello", "World", "Hi"])
print(tensor_string)

tf.Tensor([b'Hello' b'World' b'Hi'], shape=(3,), dtype=string)


##Numpy array to Tensor conversion

In [ ]:
#Convert Numpy array into tensors
import numpy as np

np_array = [1,2,3,4]
print(np_array)

[1, 2, 3, 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
#Other library functions

In [ ]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns = None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)


In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100, #most of the value will be sorround to 100, because mean is normally distributed
    stddev = 1.0, #if we increase this, the bell shaped curve will wider and decrease will result in narrow. wider means higher chance of getting a value
    dtype = tf.dtypes.float32,
    seed = None,
    name = None

)
print(random_tensor)

tf.Tensor(
[[ 99.423096 100.332535]
 [ 98.934364  99.05152 ]
 [ 99.74211  100.556145]], shape=(3, 2), dtype=float32)


Resources:
1. https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Uniform
2. https://www.acsu.buffalo.edu/~adamcunn/probability/chisquared.html
3.

In [ ]:
uniform_tensor = tf.random.uniform( #uniform means: there is equal chances for each value to pick
    [3,2,3],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor(
[[[0.99177897 0.4779985  0.73795116]
  [0.00489402 0.4196961  0.2520473 ]]

 [[0.8480005  0.5238763  0.5981821 ]
  [0.89925575 0.16542208 0.46137154]]

 [[0.6901219  0.3347075  0.4698218 ]
  [0.9254482  0.39886558 0.8932642 ]]], shape=(3, 2, 3), dtype=float32)


#Tensor Indexing

In [ ]:
tensor_one_d = ([12,34,-9,89,45])
#extracting index 1 to 3 values
print(tensor_one_d[1:4]) #[minIndex : maxIndex+1]

[34, -9, 89]


In [ ]:
print(tensor_one_d[:3]) #minIndex =0

[12, 34, -9]


In [ ]:
print(tensor_one_d[2:]) #maxIndex = last index

[-9, 89, 45]


In [ ]:
print(tensor_one_d[2:-1]) # one element will remain cut from the last

[-9, 89]


In [ ]:
#2D tensor indexing
tensor_two_d = tf.constant([
    [1,30,5],
    [45,-9,78]
])
print(tensor_two_d[ 1:, 0:3]) #[row,column]

tf.Tensor([[45 -9 78]], shape=(1, 3), dtype=int32)


In [ ]:
print(tensor_two_d[...,1]) #[pick all indexex, of column]

tf.Tensor([30 -9], shape=(2,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
                [[1,2,3],
                 [34,35,36]],

                [[-9,-8,-7],
                 [4,6,8]],

                [[5,6,0],
                 [40,56,89]],

                [[56,7,8],
                 [8,90,6777]]
])
print(tensor_three_d)

tf.Tensor(
[[[   1    2    3]
  [  34   35   36]]

 [[  -9   -8   -7]
  [   4    6    8]]

 [[   5    6    0]
  [  40   56   89]]

 [[  56    7    8]
  [   8   90 6777]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d[0:1, :-1, 0:2]) #3D means there will be 03 commas and [row : col]

tf.Tensor([[[1 2]]], shape=(1, 1, 2), dtype=int32)


In [ ]:
print(tensor_three_d[0:2, :, 2]) # : means take all, 2 means take col no 2

tf.Tensor(
[[ 3 36]
 [-7  8]], shape=(2, 2), dtype=int32)


In [ ]:
print(tensor_three_d[..., :, 2]) #means take all the elements

tf.Tensor(
[[   3   36]
 [  -7    8]
 [   0   89]
 [   8 6777]], shape=(4, 2), dtype=int32)


#Some algebra operations

In [ ]:
#Complex number
tensor_complex = tf.constant([2.23-4j])
print(abs(tensor_complex))

tf.Tensor([4.57961789], shape=(1,), dtype=float64)


In [ ]:
tf.sqrt(2.23**2 + (-4)**2)

<tf.Tensor: shape=(), dtype=float32, numpy=4.579618>

In [ ]:
x1 = tf.constant([12,4,5,6])
x2 = tf.constant([10,20,30,40])
tf.add(x1, x2)
tf.multiply(x1,x2)
tf.divide(x1,x2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1.2       , 0.2       , 0.16666667, 0.15      ])>

In [ ]:
#Broadcasting: where a tensor stretched out to operation with bigger size tensor
x1 = tf.constant([12,4,5,6])
x2 = tf.constant([4])
tf.add(x1,x2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([16,  8,  9, 10], dtype=int32)>

In [ ]:
#Max value of a tensor
print(tf.math.argmax(x1)) #will return the index of max value

tf.Tensor(0, shape=(), dtype=int64)
